- hosts: localhost
  tasks:
   - name: updates apt
     apt: update_cache=yes

   - name: install python-pycurl
     apt: pkg=python-pycurl state=installed

   - name: install pip
     apt: pkg=python-pip state=installed

   - name: install docker-py
     pip: name=docker-py

#   - name: built and install Dockernet (using Mininet installer)
#     shell: dockernet/util/install.sh
#     args:
#       chdir: ../../

#   - name: install Dockernet Python egg
#     shell: python setup.py install
#     args:
#       chdir: ../
